### ISSUE TITLE
Double tap on back to exit.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#221]
These days in most of the apps like paytm, flipkart etc when we press back button a Toast appears which says "press again to exit" or something similar. 
![paytm](https://cloud.githubusercontent.com/assets/17262180/20206633/d58383c2-a807-11e6-98a9-885cde3808f6.png)
Paytm

![flipkart](https://cloud.githubusercontent.com/assets/17262180/20206634/d92f54d8-a807-11e6-86b9-5d908ae7b3ec.png)
Flipkart

If the user presses back once again within 2 seconds the the app is closed.

Should I implement this and send a PR.

**Comment by free4murad** [comment]
Implemented the functionality in PR #223

**Comment by saketkumar95** [comment]
I also thought of this feature but  it is only suitable for games, or app which has sessions like banking apps, computer based tests, etc. The reason why UX designers put this feature in an app is because they do not want the user kill a session unknowingly and may be getting to the home screen the app requires a lot of verification.

Getting to the home screen is just a tap away in this app so no need for that prompt. If a user mistakenly exit, getting back to is just a tap away. It is just a suggestion if @opticod @croozeus  wants this then do implement this feature but for my suggestion , it is not required.

**Comment by opticod** [comment]
@saketkumar95 , Lets do some experiment. If we found it not useful, we can remove it in near future.

**Comment by opticod** [comment]
Closed via #237
